language: node_js
node_js:
    - '11.10.1'
cache:
    yarn: true
    directories:
        - node_modules
        - client/node_modules
before_install:
    - sudo apt-get install -y lcov
install:
    - yarn install-all
script:
    - yarn coverage
    - yarn --cwd client build
after_script: # Upload coverage reports
    - yarn coveralls
