language: node_js
node_js:
    - '11'
services:
    - mongodb
before_install:
    - sudo apt-get install -y lcov
install:
    - yarn install-all
script:
    - yarn client:coverage
    - yarn server:coverage
    - yarn --cwd client build
after_script: # Upload coverage reports
    - yarn coveralls
