matrix:
    include:
        - language: node_js
          node_js:
              - '8'
              - '10'
              - '11'
          cache:
              yarn: true
              directories:
                  - node_modules
                  - client/node_modules
          services:
              - mongodb
          before_install:
              - sudo apt-get install -y lcov
              - sudo apt-get install python3
          install:
              - yarn install-all
          script:
              - yarn client:coverage
              - yarn server:coverage
              - yarn --cwd client build
          after_script: # Upload coverage reports
              - yarn coveralls

        - language: python
          python:
              - '3.6'
          addons:
              sauce_connect: true
          before_install:
              - cd selenium-tests
          script:
              - python3 *.py
