language: node_js
node_js:
    - '8'
    - '10'
    - '11'
services:
    - mongodb
install:
    - yarn all-install
script:
    - yarn test -- --coverage
    - yarn --cwd client build
after_script: # Upload coverage reports
    - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
