language: node_js
node_js:
    - '8'
    - '10'
    - '11'
cache:
    yarn: true
    directories:
        - node_modules
        - client/node_modules
addons:
    sauce_connect: true
services:
    - mongodb
before_install:
    - sudo apt-get install -y lcov
    - sudo apt-get install python3
install:
    - yarn install-all
    - pip3 install pipenv
    - yarn install-selenium
script:
    - yarn test:selenium
    - yarn client:coverage
    - yarn server:coverage
    - yarn --cwd client build
after_script: # Upload coverage reports
    - yarn coveralls
