language: node_js
node_js:
    - '11.10.1'
cache:
    npm: true
    directories:
        - node_modules
        - client/node_modules
before_install:
    - sudo apt-get install -y lcov
install:
    - npm run install-all
script:
    - npm run coverage
    - npm run --prefix client build
after_script: # Upload coverage reports
    - npm run coveralls
