// error action types
export const GET_ERRORS = 'GET_ERRORS';

// auth action types
export const ADMIN_LOADING = 'ADMIN_LOADING';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';

// admin action types
export const FETCH_ADMINS_BEGIN = 'FETCH_ADMINS_BEGIN';
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS';
export const FETCH_ADMIN_BEGIN = 'FETCH_ADMIN_BEGIN';
export const FETCH_ADMIN_SUCCESS = 'FETCH_ADMIN_SUCCESS';

// volunteer action types
export const FETCH_VOLUNTEERS_BEGIN = 'FETCH_VOLUNTEERS_BEGIN';
export const FETCH_VOLUNTEERS_SUCCESS = 'FETCH_VOLUNTEERS_SUCCESS';
export const FETCH_VOLUNTEER_BEGIN = 'FETCH_VOLUNTEER_BEGIN';
export const FETCH_VOLUNTEER_SUCCESS = 'FETCH_VOLUNTEER_SUCCESS';

// member action types
export const FETCH_MEMBERS_BEGIN = 'FETCH_MEMBERS_BEGIN';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBER_BEGIN = 'FETCH_MEMBER_BEGIN';
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS';
export const MODIFY_MEMBER_BEGIN = 'MODIFY_MEMBER_BEGIN';
export const MODIFY_MEMBER_SUCCESS = 'MODIFY_MEMBER_SUCCESS';

// activity action Types
export const FETCH_ACTIVITIES_BEGIN = 'FETCH_ACTIVITIES_BEGIN';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITY_BEGIN = 'FETCH_ACTIVITY_BEGIN';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FILTER_ACTIVITIES_BEGIN = 'FILTER_ACTIVITIES_BEGIN';
export const FILTER_ACTIVITIES_SUCCESS = 'FILTER_ACTIVITIES_SUCCESS';
